version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: 1234
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cap_alert
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.docker
    depends_on:
      - db
      - redis

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - db
    env_file:
      - ./.env.docker
    command: celery -A project worker -l info --pool=solo

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - db
    env_file:
      - ./.env.docker
    command: celery -A project beat -l info -s celerybeat-schedule

volumes:
  postgres_data:
