# Generated by Django 4.2.2 on 2023-06-22 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='None')),
                ('polygon', models.CharField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('whatsapp_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='whatsapp')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('category', models.CharField(default='', verbose_name='category')),
                ('urgency', models.IntegerField(default='', verbose_name='urgency')),
                ('severity', models.IntegerField(default='', verbose_name='severity')),
                ('subscribe_by', models.CharField(default='', verbose_name='subscribe_by')),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_id', to='subscription_dir.region')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='subscription_dir.user')),
            ],
        ),
    ]
