# Generated by Django 4.2.2 on 2023-06-23 16:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0, verbose_name='user_id')),
                ('country_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='country_ids'), default=list, size=None)),
                ('category', models.CharField(default='', verbose_name='category')),
                ('urgency', models.IntegerField(default=0, verbose_name='urgency')),
                ('severity', models.IntegerField(default=0, verbose_name='severity')),
                ('subscribe_by', models.CharField(default='', verbose_name='subscribe_by')),
            ],
        ),
    ]
