# Generated by Django 4.2.2 on 2023-06-22 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_dir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='subscription_dir.region'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='subscription_dir.user'),
        ),
    ]
