# Generated by Django 4.2.2 on 2023-06-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_dir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_name',
            field=models.CharField(default='', verbose_name='subscription_name'),
        ),
    ]
