# Generated by Django 4.2.2 on 2023-08-02 09:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_dir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='district_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='district_ids'), default=list, size=None),
        ),
    ]
