# Generated by Django 4.2.2 on 2023-08-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_dir', '0002_subscription_district_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='sent_flag',
            field=models.IntegerField(default=0, verbose_name='sent_flag'),
        ),
    ]
