# Generated by Django 4.2.2 on 2023-08-10 15:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_dir', '0003_subscription_sent_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='district_ids',
        ),
        migrations.AddField(
            model_name='subscription',
            name='admin1_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='admin1_ids'), default=list, size=None),
        ),
    ]
