# Generated by Django 4.2.2 on 2023-06-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dir', '0004_customuser_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_reset_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_reset_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
