# Generated by Django 4.2.2 on 2023-07-07 18:35

from django.db import migrations, models
import user_dir.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user_dir', '0006_remove_customuser_email_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='jti',
            field=models.CharField(default=user_dir.utils.generate_jti, editable=False, help_text='JWT tokens for the user get revoked when JWT id has regenerated.', max_length=64, verbose_name='jwt id'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='username'),
        ),
    ]
