# Generated by Django 4.2.2 on 2023-07-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dir', '0006_remove_customuser_email_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(blank=True, null=True),
        ),
    ]
