# Generated by Django 4.2.2 on 2023-07-06 01:08

from django.db import migrations, models
import user_dir.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user_dir', '0007_alter_customuser_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='jti',
            field=models.CharField(default=user_dir.utils.generate_jti, editable=False, help_text='JWT tokens for the user get revoked when JWT id has regenerated.', max_length=64, verbose_name='jwt id'),
        ),
    ]
