# Generated by Django 4.2.3 on 2023-07-16 20:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField()),
                ('processed_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='None')),
                ('polygon', models.CharField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='None')),
                ('society_name', models.CharField(default='None')),
                ('polygon', models.CharField(default='None')),
                ('centroid', models.CharField(default='None')),
                ('region_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_id', to='filter.region')),
            ],
        ),
        migrations.CreateModel(
            name='AlertInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='no category')),
                ('event', models.CharField(default='hazard')),
                ('urgency', models.CharField(default='low')),
                ('severity', models.CharField(default='low')),
                ('certainty', models.CharField(default='low')),
                ('effective', models.CharField(default=datetime.datetime(2023, 7, 16, 20, 2, 42, 411439, tzinfo=datetime.timezone.utc))),
                ('headline', models.CharField(default='Empty Headline', max_length=100)),
                ('description', models.CharField(default='Empty Description', max_length=255)),
                ('instruction', models.CharField(default='Empty Instruction', max_length=255)),
                ('senderName', models.CharField(default='Null', max_length=100)),
                ('areaDesc', models.CharField(default='None', max_length=255)),
                ('polygon', models.CharField(default='None', max_length=255)),
                ('geocode_name', models.CharField(default='None')),
                ('geocode_value', models.CharField(default='None')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='filter.alert')),
            ],
        ),
    ]
