# Generated by Django 4.2.2 on 2023-06-14 13:53

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='integer',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='name',
        ),
        migrations.AddField(
            model_name='alert',
            name='areaDesc',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='alert',
            name='category',
            field=models.CharField(default='no category'),
        ),
        migrations.AddField(
            model_name='alert',
            name='certainty',
            field=models.CharField(default='low'),
        ),
        migrations.AddField(
            model_name='alert',
            name='description',
            field=models.CharField(default='Empty Description', max_length=255),
        ),
        migrations.AddField(
            model_name='alert',
            name='effective',
            field=models.CharField(default=datetime.datetime(2023, 6, 14, 13, 52, 54, 614699, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='alert',
            name='event',
            field=models.CharField(default='hazard'),
        ),
        migrations.AddField(
            model_name='alert',
            name='geocode_name',
            field=models.CharField(default='None'),
        ),
        migrations.AddField(
            model_name='alert',
            name='geocode_value',
            field=models.CharField(default='None'),
        ),
        migrations.AddField(
            model_name='alert',
            name='headline',
            field=models.CharField(default='Empty Headline', max_length=100),
        ),
        migrations.AddField(
            model_name='alert',
            name='instruction',
            field=models.CharField(default='Empty Instruction', max_length=255),
        ),
        migrations.AddField(
            model_name='alert',
            name='polygon',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='processed_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='senderName',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(default='low'),
        ),
        migrations.AddField(
            model_name='alert',
            name='urgency',
            field=models.CharField(default='low'),
        ),
    ]
