# Generated by Django 4.2.3 on 2023-07-26 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertinfo',
            name='effective',
            field=models.CharField(default=datetime.datetime(2023, 7, 26, 2, 2, 52, 252027, tzinfo=datetime.timezone.utc)),
        ),
    ]
