# Generated by Django 4.2.3 on 2023-07-26 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_alter_alertinfo_effective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertinfo',
            name='effective',
            field=models.CharField(default=datetime.datetime(2023, 7, 26, 2, 3, 17, 642918, tzinfo=datetime.timezone.utc)),
        ),
    ]
