# Generated by Django 4.2.2 on 2023-06-19 00:07

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_remove_alert_creation_date_remove_alert_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='areaDesc',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='category',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='certainty',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='description',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='effective',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='event',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='geocode_name',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='geocode_value',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='polygon',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='senderName',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='urgency',
        ),
        migrations.AddField(
            model_name='alert',
            name='hash_id',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AlertInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='no category')),
                ('event', models.CharField(default='hazard')),
                ('urgency', models.CharField(default='low')),
                ('severity', models.CharField(default='low')),
                ('certainty', models.CharField(default='low')),
                ('effective', models.CharField(default=datetime.datetime(2023, 6, 19, 0, 6, 35, 236159, tzinfo=datetime.timezone.utc))),
                ('headline', models.CharField(default='Empty Headline', max_length=100)),
                ('description', models.CharField(default='Empty Description', max_length=255)),
                ('instruction', models.CharField(default='Empty Instruction', max_length=255)),
                ('areaDesc', models.CharField(default='None', max_length=255)),
                ('polygon', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('geocode_name', models.CharField(default='None')),
                ('geocode_value', models.CharField(default='None')),
                ('senderName', models.CharField(default='Null', max_length=100)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='filter.alert')),
            ],
        ),
    ]
