# Generated by Django 4.2.3 on 2023-07-28 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0003_alter_alertinfo_effective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertinfo',
            name='effective',
            field=models.CharField(default=datetime.datetime(2023, 7, 28, 1, 54, 23, 653013, tzinfo=datetime.timezone.utc)),
        ),
    ]
