# Generated by Django 4.2.2 on 2023-06-19 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0004_region_alter_alertinfo_effective_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='centroid',
        ),
        migrations.AlterField(
            model_name='alertinfo',
            name='effective',
            field=models.CharField(default=datetime.datetime(2023, 6, 19, 22, 25, 44, 745178, tzinfo=datetime.timezone.utc)),
        ),
    ]
