# Generated by Django 4.2.3 on 2023-07-31 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0004_alter_alertinfo_effective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertinfo',
            name='effective',
            field=models.CharField(default=datetime.datetime(2023, 7, 31, 0, 45, 43, 755180, tzinfo=datetime.timezone.utc)),
        ),
    ]
