# Generated by Django 4.2.2 on 2023-06-19 23:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0005_remove_region_centroid_alter_alert_processed_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertinfo',
            name='effective',
            field=models.CharField(default=datetime.datetime(2023, 6, 19, 23, 42, 3, 220766, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='country',
            name='region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_id', to='filter.region'),
        ),
    ]
