# Generated by Django 4.2.2 on 2023-06-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_dir', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='whatsapp_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsAppId',
            field=models.EmailField(max_length=254, null=True, verbose_name='whatsAppId'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
