# Generated by Django 4.2.2 on 2023-06-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_dir', '0004_alter_customuser_whatsappid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='whatsAppId',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phoneNumber',
            field=models.CharField(max_length=254, null=True, unique=True, verbose_name='phone'),
        ),
    ]
