# Generated by Django 4.2.2 on 2023-06-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_dir', '0006_alter_customuser_avatar_alter_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
