# Generated by Django 4.2.3 on 2023-07-26 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=255)),
                ('country_id', models.CharField(max_length=255)),
                ('source_feed', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=255)),
                ('urgency', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=255)),
                ('certainty', models.CharField(max_length=255)),
                ('info', models.JSONField()),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
