# Generated by Django 4.2.3 on 2023-08-17 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_manager_dir', 'test_migrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capfeedadmin1',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='capfeedalert',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='capfeedalertadmin1',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='capfeedalertinfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='capfeedcountry',
            options={'managed': False},
        ),
    ]
