# Generated by Django 4.2.3 on 2023-08-07 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_dir', '0003_subscription_sent_flag'),
        ('subscription_manager_dir', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionalerts',
            name='id',
        ),
        migrations.AlterField(
            model_name='subscriptionalerts',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='subscription_dir.subscription'),
        ),
    ]
