# Generated by Django 4.2.3 on 2023-08-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_manager_dir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionalerts',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
